#!/usr/bin/env python3
"""
Geometric Hallucination Taxonomy — Spectral Band Decomposition
=================================================================

Decomposes contextual hidden states into eigenspectrum bands and tests
each band separately for hallucination-type separation. Tests two
competing hypotheses for the Type 1/2 non-separation found in Paper 2:

  Spectral mixing hypothesis: The Type 1/2 signal exists but is
    concentrated in specific eigenspectrum bands, diluted when
    full-dimensional metrics aggregate across all components.
  Capacity hypothesis: The Type 1/2 signal does not exist at 124M
    parameters — the model lacks representational precision for this
    distinction.

Result: The spectral mixing hypothesis is rejected. Type 1/2 does not
survive prompt-level aggregation in any spectral band (best p = 0.082).
The Type 3 signal is spectrally structured: angular metrics in mid-range
components, magnitude in the tail, dead zone at PCs 17-48.

Architecture:
  1. Generate calibration + experimental hidden states (same as whitened)
  2. Compute full PCA on calibration (768 components)
  3. Define spectral bands across the eigenspectrum
  4. For each band: project → whiten → cluster → measure → test
  5. Sliding window scan across eigenspectrum
  6. Two-level analysis: prompt-level (N=15, primary) + token-level (reference)

NOTE: Publication figures for Paper 3 are generated by generate_figures.py
from the summary_spectral.json output, not by this script's internal
figure generation. The figures below are diagnostic/exploratory.

Outputs (in ./results_induction_spectral/):
  - induction_spectral_report.txt     : full results with per-band tests
  - fig_spectral_bands.png            : KW p-values per band (all pairs)
  - fig_spectral_scan.png             : sliding window scan
  - fig_eigenspectrum.png             : eigenvalue distribution + variance
  - summary_spectral.json             : machine-readable results

Hardware: CPU only, ~4–8GB RAM, ~25–40 min runtime
Usage:  python hallucination_induction_spectral.py
"""

import os
import sys
import time
import gc
import json
import warnings
import numpy as np
from scipy import stats
from sklearn.cluster import MiniBatchKMeans
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

from hallucination_stats import (
    extract_prompt_metrics_raw, run_two_level_tests, token_diagnostics,
    format_stats_report, format_band_report, format_survivors_summary,
    results_to_json, holm_bonferroni, SEED,
)

# ──────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────────────

CONFIG = {
    'n_clusters': 40,
    'random_seed': 42,
    'output_dir': './results_induction_spectral',
    'figure_dpi': 150,
    'generate_figures': True,    # set False to skip diagnostic figure generation

    # Generation
    'max_new_tokens': 60,
    'temperature': 1.0,
    'top_k': 0,
    'top_p': 1.0,

    # Calibration
    'n_calibration_prompts': 25,
    'calibration_tokens': 60,

    # Spectral bands — logarithmic spacing to match eigenvalue decay
    # Each band is (start_pc, end_pc) — 0-indexed, inclusive
    'bands': [
        (0,   15,  'PC 1–16\n(dominant)'),
        (16,  47,  'PC 17–48'),
        (48,  127, 'PC 49–128'),
        (128, 255, 'PC 129–256'),
        (256, 511, 'PC 257–512'),
        (512, 767, 'PC 513–768\n(tail)'),
    ],

    # Sliding window scan
    'scan_width': 64,           # width of each window
    'scan_step': 32,            # step size
    'scan_max_pc': 768,         # scan up to this PC

    # Whitening regularization
    'whiten_reg': 1e-5,
}


# ──────────────────────────────────────────────────────────────────────
# PROMPT SETS (identical to all previous experiments)
# ──────────────────────────────────────────────────────────────────────

TYPE1_PROMPTS = [
    "The", "It is", "There are", "This is a", "One of the",
    "In the", "As a", "They were", "Some of", "Many people",
    "It was a", "He said that", "The most", "We have", "A very",
]

TYPE2_PROMPTS = [
    "The bank announced record levels of",
    "The pitch was perfect for the",
    "She picked up the bat and",
    "The board decided to table the",
    "He studied the cell under the",
    "The crane lifted the heavy",
    "The plant manager reviewed the new",
    "Mercury levels in the",
    "The current was too strong for the",
    "The cabinet members discussed the",
    "They found the mole in the",
    "The scales showed exactly",
    "The press released a statement about the",
    "The match was struck and",
    "The patient leaves were carefully",
]

TYPE3_PROMPTS = [
    "The xenoplasmic refractometry of late-Holocene",
    "Professor Kvistad's third theorem on paracompact",
    "In Zvrotkian epistemology, the concept of mereological",
    "The biosemiotic implications of CRISPR-modified Tardigrade",
    "According to the Nørgaard-Patel conjecture in topological",
    "The post-Deleuzian analysis of quantum decoherence in",
    "Hyperbolic crochet models of anti-de Sitter spacetime suggest",
    "The ethnopharmacological study of Amazonian Ayahuasca analogs",
    "A contravariant functor from the category of smooth manifolds",
    "The archaeomagnetostratigraphic evidence from Paleocene",
    "Subquadratic approximation algorithms for the Steiner tree",
    "The phenomenological reduction of eigenstate thermalization",
    "Applying Khovanov homology to categorified quantum groups",
    "The gliotransmitter-mediated modulation of thalamocortical",
    "Transfinite induction over the constructible hierarchy L",
]

CALIBRATION_PROMPTS = [
    "The president of the United States delivered a speech about",
    "Scientists at the university discovered a new species of",
    "The stock market experienced significant volatility after the",
    "In a landmark court ruling, the judge determined that",
    "The new software update includes several improvements to",
    "Researchers published a study showing that regular exercise",
    "The city council voted unanimously to approve the construction of",
    "According to the latest census data, the population of",
    "The chef prepared a traditional Italian dish using fresh",
    "Engineers at the space agency successfully launched the",
    "The novel, which was published last year, tells the story of",
    "Climate scientists warned that global temperatures could rise",
    "The football team won their fifth consecutive game by",
    "Historians have long debated whether the ancient civilization",
    "The pharmaceutical company announced positive results from",
    "A major earthquake measuring seven on the Richter scale struck",
    "The documentary explores the lives of immigrant families who",
    "Economists predict that inflation will continue to affect",
    "The orchestra performed Beethoven's ninth symphony to a",
    "Marine biologists observed unusual behavior in the population of",
    "The school board implemented a new curriculum focused on",
    "Astronomers detected a faint signal coming from a distant",
    "The factory produces over ten thousand units per day of",
    "Political analysts suggest that the upcoming election will be",
    "The museum's latest exhibition features artwork from the",
]


# ──────────────────────────────────────────────────────────────────────
# MODEL LOADING AND GENERATION (reused from whitened script)
# ──────────────────────────────────────────────────────────────────────

def load_gpt2():
    print("\n[Step 1] Loading GPT-2...")
    t0 = time.time()

    import torch
    from transformers import GPT2LMHeadModel, GPT2Tokenizer

    tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
    model = GPT2LMHeadModel.from_pretrained('gpt2', torch_dtype=torch.float32)
    model.eval()

    with torch.no_grad():
        static_emb = model.transformer.wte.weight.cpu().numpy()

    print(f"  Model loaded in {time.time() - t0:.1f}s")
    return model, tokenizer, static_emb


def generate_with_hidden_states(model, tokenizer, prompt, max_new_tokens,
                                temperature=1.0, top_k=0, top_p=1.0):
    """Manual autoregressive generation capturing last-layer hidden states."""
    import torch

    input_ids = tokenizer.encode(prompt, return_tensors='pt')
    generated_ids = []
    hidden_states_list = []

    eos_id = tokenizer.eos_token_id

    for step in range(max_new_tokens):
        with torch.no_grad():
            outputs = model(input_ids, output_hidden_states=True)

        last_hidden = outputs.hidden_states[-1][:, -1, :]  # (1, 768)
        logits = outputs.logits[:, -1, :]

        if temperature != 1.0:
            logits = logits / temperature
        if top_k > 0:
            indices_to_remove = logits < torch.topk(logits, top_k)[0][..., -1, None]
            logits[indices_to_remove] = float('-inf')
        if top_p < 1.0:
            sorted_logits, sorted_indices = torch.sort(logits, descending=True)
            cumulative_probs = torch.cumsum(torch.softmax(sorted_logits, dim=-1), dim=-1)
            sorted_indices_to_remove = cumulative_probs > top_p
            sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
            sorted_indices_to_remove[..., 0] = 0
            indices_to_remove = sorted_indices_to_remove.scatter(
                1, sorted_indices, sorted_indices_to_remove)
            logits[indices_to_remove] = float('-inf')

        probs = torch.softmax(logits, dim=-1)
        next_token = torch.multinomial(probs, num_samples=1)

        token_id = next_token.item()
        if token_id == eos_id:
            break

        generated_ids.append(token_id)
        hidden_states_list.append(last_hidden.squeeze(0).cpu().numpy())
        input_ids = torch.cat([input_ids, next_token], dim=1)

    hidden_states = np.array(hidden_states_list) if hidden_states_list else np.zeros((0, 768))
    generated_text = tokenizer.decode(generated_ids, skip_special_tokens=True)
    return generated_ids, hidden_states, generated_text


def build_calibration(model, tokenizer):
    """Generate calibration hidden states."""
    print("\n[Step 2] Building calibration distribution...")
    t0 = time.time()

    all_hidden = []
    for i, prompt in enumerate(CALIBRATION_PROMPTS):
        gen_ids, hidden, gen_text = generate_with_hidden_states(
            model, tokenizer, prompt,
            max_new_tokens=CONFIG['calibration_tokens'],
            temperature=CONFIG['temperature'],
            top_k=CONFIG['top_k'], top_p=CONFIG['top_p'])
        if len(hidden) > 0:
            all_hidden.append(hidden)
        if (i + 1) % 5 == 0:
            n = sum(h.shape[0] for h in all_hidden)
            print(f"    Calibration: {i+1}/{len(CALIBRATION_PROMPTS)} prompts, {n} tokens")

    calibration_hidden = np.vstack(all_hidden)
    print(f"  Calibration: {calibration_hidden.shape[0]} vectors × {calibration_hidden.shape[1]}D")
    print(f"  Done in {time.time() - t0:.1f}s")
    return calibration_hidden


def generate_experimental(model, tokenizer, prompts, type_label):
    """Generate experimental sequences, returning raw hidden states."""
    print(f"\n  Generating {type_label}...")
    results = []
    for i, prompt in enumerate(prompts):
        gen_ids, hidden, gen_text = generate_with_hidden_states(
            model, tokenizer, prompt,
            max_new_tokens=CONFIG['max_new_tokens'],
            temperature=CONFIG['temperature'],
            top_k=CONFIG['top_k'], top_p=CONFIG['top_p'])
        results.append({
            'type': type_label,
            'prompt': prompt,
            'generated_text': gen_text,
            'token_ids': gen_ids,
            'hidden_states': hidden,  # raw 768D hidden states
            '_max_tokens': CONFIG['max_new_tokens'],
        })
        if (i + 1) % 5 == 0:
            print(f"    {type_label}: {i+1}/{len(prompts)} prompts")
    return results


# ──────────────────────────────────────────────────────────────────────
# SPECTRAL DECOMPOSITION
# ──────────────────────────────────────────────────────────────────────

def compute_full_pca(calibration_hidden):
    """Compute full PCA on calibration data — we need all 768 components."""
    print("\n[Step 3] Computing full PCA decomposition...")
    t0 = time.time()

    mean = calibration_hidden.mean(axis=0)
    centered = calibration_hidden - mean

    # Full PCA — all components
    n_components = min(calibration_hidden.shape[0] - 1, calibration_hidden.shape[1])
    pca = PCA(n_components=n_components, random_state=CONFIG['random_seed'])
    pca.fit(centered)

    eigenvalues = pca.explained_variance_
    cumvar = np.cumsum(pca.explained_variance_ratio_)

    print(f"  Components computed: {n_components}")
    print(f"  Eigenvalue range: [{eigenvalues[-1]:.4f}, {eigenvalues[0]:.4f}]")
    print(f"  Top 10 PCs: {cumvar[9]:.1%} variance")
    print(f"  Top 50 PCs: {cumvar[49]:.1%} variance")
    print(f"  Top 100 PCs: {cumvar[99]:.1%} variance")
    print(f"  Top 256 PCs: {cumvar[255]:.1%} variance")
    print(f"  Done in {time.time() - t0:.1f}s")

    return mean, pca, eigenvalues, cumvar


def analyze_band(calibration_hidden, all_experimental, mean, pca, eigenvalues,
                 band_start, band_end, band_label, reg=1e-5):
    """Analyze a single spectral band with two-level testing.

    Projects all vectors onto PCs [band_start:band_end+1], whitens
    within that subspace, clusters, and computes geometric metrics.
    Preserves per-prompt structure for prompt-level testing.

    Returns dict with two-level test results + band metadata.
    """
    n_pcs = band_end - band_start + 1

    # Band projection matrix: select PCs and whiten
    components = pca.components_[band_start:band_end+1]  # (n_pcs, 768)
    band_eigenvalues = eigenvalues[band_start:band_end+1]
    scale = 1.0 / np.sqrt(band_eigenvalues + reg)

    # Whitening matrix for this band: project then scale
    W_band = components.T * scale  # (768, n_pcs)

    # Transform calibration
    centered_calib = calibration_hidden - mean
    whitened_calib = centered_calib @ W_band  # (n_calib, n_pcs)

    # Cluster in this band's whitened space
    n_clusters = min(CONFIG['n_clusters'], max(10, n_pcs // 2))
    kmeans = MiniBatchKMeans(
        n_clusters=n_clusters, random_state=CONFIG['random_seed'],
        batch_size=min(1024, whitened_calib.shape[0]),
        max_iter=300, n_init=5)
    kmeans.fit(whitened_calib)
    centroids = kmeans.cluster_centers_

    # Define compute function for this band (closure over W_band, centroids)
    def compute_band_metrics(hidden_states):
        centered = hidden_states - mean
        whitened = centered @ W_band
        sims = cosine_similarity(whitened, centroids)
        top_k = min(5, sims.shape[1])
        top_sims = np.sort(sims, axis=1)[:, -top_k:]
        return {
            'H': top_sims.mean(axis=1),
            'max_sim': sims.max(axis=1),
            'norm': np.linalg.norm(whitened, axis=1),
        }

    # Extract with per-prompt structure preserved
    prompt_data, token_data, diagnostics = extract_prompt_metrics_raw(
        all_experimental, compute_band_metrics)

    # Run two-level tests
    two_level = run_two_level_tests(
        prompt_data, token_data,
        metric_names=['H', 'max_sim', 'norm'],
        cfg={'n_permutations': 50000, 'n_bootstrap': 10000})

    # Add band metadata
    two_level['_meta'] = {
        'band_label': band_label.replace('\n', ' '),
        'band_start': band_start,
        'band_end': band_end,
        'n_pcs': n_pcs,
        'n_clusters': n_clusters,
        'variance_in_band': float(
            pca.explained_variance_ratio_[band_start:band_end+1].sum()),
    }

    # Also keep legacy token-level results for backward compat with figures
    two_level['_legacy'] = {
        'tests': {}, 'pairwise': {}, 'means': {},
    }
    types = sorted(token_data.keys())
    for metric_name in ['H', 'max_sim', 'norm']:
        groups = [token_data[t][metric_name] for t in types]
        if all(len(g) > 0 for g in groups):
            H_stat, p_val = stats.kruskal(*groups)
            N = sum(len(g) for g in groups)
            eps2 = (H_stat - len(groups) + 1) / (N - len(groups)) if N > len(groups) else 0
            two_level['_legacy']['tests'][metric_name] = {
                'H': float(H_stat), 'p': float(p_val), 'eps2': float(eps2)
            }
        for i, t1 in enumerate(types):
            for t2 in types[i+1:]:
                g1, g2 = token_data[t1][metric_name], token_data[t2][metric_name]
                if len(g1) > 0 and len(g2) > 0:
                    U, p = stats.mannwhitneyu(g1, g2, alternative='two-sided')
                    n1, n2 = len(g1), len(g2)
                    r = 1 - (2 * U) / (n1 * n2)
                    two_level['_legacy']['pairwise'][f"{metric_name}_{t1}_vs_{t2}"] = {
                        'U': float(U), 'p': float(p), 'r': float(r),
                        'mean_1': float(g1.mean()), 'mean_2': float(g2.mean()),
                    }
    for ctype in types:
        two_level['_legacy']['means'][ctype] = {}
        for metric_name in ['H', 'max_sim', 'norm']:
            arr = token_data[ctype][metric_name]
            two_level['_legacy']['means'][ctype][metric_name] = {
                'mean': float(arr.mean()), 'std': float(arr.std()),
            }

    return two_level


def run_sliding_scan(calibration_hidden, all_experimental, mean, pca,
                     eigenvalues, width, step, max_pc):
    """Sliding window scan across the eigenspectrum."""
    print(f"\n[Step 5b] Sliding window scan (width={width}, step={step})...")
    t0 = time.time()

    max_available = len(eigenvalues)
    scan_limit = min(max_pc, max_available)
    scan_results = []

    starts = list(range(0, scan_limit - width + 1, step))
    for i, start in enumerate(starts):
        end = start + width - 1
        r = analyze_band(calibration_hidden, all_experimental, mean, pca,
                         eigenvalues, start, end, f"PC {start+1}–{end+1}")
        scan_results.append(r)
        if (i + 1) % 5 == 0 or i == len(starts) - 1:
            print(f"    Scan: {i+1}/{len(starts)} windows")

    print(f"  Scan complete in {time.time() - t0:.1f}s")
    return scan_results


def add_legacy_compat(br):
    """Add old-format keys to a two-level band result for figure/report compat.

    The figures and parts of write_report access br['pairwise'], br['tests'],
    br['band_label'] etc. This function maps those from the new two-level
    structure's _legacy and _meta fields.
    """
    meta = br.get('_meta', {})
    legacy = br.get('_legacy', {})
    br['band_label'] = meta.get('band_label', '')
    br['band_start'] = meta.get('band_start', 0)
    br['band_end'] = meta.get('band_end', 0)
    br['n_pcs'] = meta.get('n_pcs', 0)
    br['n_clusters'] = meta.get('n_clusters', 0)
    br['variance_in_band'] = meta.get('variance_in_band', 0)
    br['tests'] = legacy.get('tests', {})
    br['pairwise'] = legacy.get('pairwise', {})
    br['means'] = legacy.get('means', {})
    return br


# ──────────────────────────────────────────────────────────────────────
# FIGURES
# ──────────────────────────────────────────────────────────────────────

def generate_figures(band_results, scan_results, eigenvalues, cumvar,
                     output_dir):
    """Generate all spectral analysis figures."""
    dpi = CONFIG['figure_dpi']

    # ── Figure 1: Eigenspectrum ──────────────────────────────────────
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    n_ev = min(768, len(eigenvalues))
    ax1.semilogy(range(1, n_ev+1), eigenvalues[:n_ev], '-', color='#2c3e50',
                 linewidth=1.5)
    # Mark band boundaries
    colors = ['#e74c3c', '#f39c12', '#2ecc71', '#3498db', '#9b59b6', '#1abc9c']
    for i, (start, end, label) in enumerate(CONFIG['bands']):
        if start < n_ev:
            ax1.axvspan(start+1, min(end+1, n_ev), alpha=0.15, color=colors[i % len(colors)])
            mid = (start + min(end, n_ev-1)) / 2 + 1
            ax1.text(mid, eigenvalues[0] * 0.5, label.replace('\n', ' '),
                     fontsize=7, ha='center', va='top', rotation=90, alpha=0.7)

    ax1.set_xlabel('Principal Component', fontsize=11)
    ax1.set_ylabel('Eigenvalue (log scale)', fontsize=11)
    ax1.set_title('Eigenspectrum of Contextual Hidden States', fontsize=13,
                  fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim(0, n_ev)

    # Cumulative variance
    ax2.plot(range(1, len(cumvar)+1), cumvar, '-', color='#8e44ad', linewidth=2)
    for thresh, ls in [(0.5, ':'), (0.9, '--'), (0.95, '--'), (0.99, '-.')]:
        idx = np.searchsorted(cumvar, thresh)
        ax2.axhline(y=thresh, color='gray', linestyle=ls, alpha=0.4)
        ax2.axvline(x=idx+1, color='gray', linestyle=ls, alpha=0.4)
        ax2.annotate(f'{thresh:.0%} @ PC {idx+1}', xy=(idx+1, thresh),
                     fontsize=8, xytext=(10, -10), textcoords='offset points')

    ax2.set_xlabel('Number of Components', fontsize=11)
    ax2.set_ylabel('Cumulative Variance Explained', fontsize=11)
    ax2.set_title('Cumulative Variance', fontsize=12, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.set_xlim(0, len(cumvar))

    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, 'fig_eigenspectrum.png'),
                dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print("  ✓ fig_eigenspectrum.png")

    # ── Figure 2: Per-band p-values ──────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    pairs = ['type1_vs_type2', 'type1_vs_type3', 'type2_vs_type3']
    pair_labels = ['Type 1 vs Type 2\n(drift vs commit)', 'Type 1 vs Type 3\n(drift vs gap)',
                   'Type 2 vs Type 3\n(commit vs gap)']

    for ax_idx, (pair_suffix, pair_label) in enumerate(zip(pairs, pair_labels)):
        ax = axes[ax_idx]
        band_labels = []
        for metric_name, color, marker in [('H', '#e74c3c', 'o'),
                                           ('max_sim', '#2980b9', 's'),
                                           ('norm', '#27ae60', '^')]:
            p_vals = []
            x_pos = []
            for i, br in enumerate(band_results):
                key = f"{metric_name}_{pair_suffix}"
                if key in br['pairwise']:
                    p_vals.append(br['pairwise'][key]['p'])
                    x_pos.append(i)
                if ax_idx == 0 and metric_name == 'H':
                    band_labels.append(br['band_label'])

            if p_vals:
                p_log = [-np.log10(max(p, 1e-50)) for p in p_vals]
                ax.plot(x_pos, p_log, f'-{marker}', color=color, markersize=8,
                        linewidth=1.5, alpha=0.8, label=metric_name)

        # Significance thresholds
        ax.axhline(y=-np.log10(0.05), color='gray', linestyle='--', alpha=0.5,
                   label='p = 0.05')
        ax.axhline(y=-np.log10(0.001), color='gray', linestyle=':', alpha=0.4,
                   label='p = 0.001')

        if band_labels:
            ax.set_xticks(range(len(band_labels)))
            ax.set_xticklabels(band_labels, fontsize=8, rotation=30, ha='right')
        ax.set_ylabel('-log₁₀(p)', fontsize=11)
        ax.set_title(pair_label, fontsize=12, fontweight='bold')
        ax.legend(fontsize=8, loc='upper right')
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, 'fig_spectral_bands.png'),
                dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print("  ✓ fig_spectral_bands.png")

    # ── Figure 3: Sliding window scan ────────────────────────────────
    if scan_results:
        fig, axes = plt.subplots(3, 1, figsize=(14, 12), sharex=True)

        for ax_idx, (pair_suffix, pair_label) in enumerate(zip(pairs, pair_labels)):
            ax = axes[ax_idx]

            for metric_name, color in [('H', '#e74c3c'), ('max_sim', '#2980b9'),
                                       ('norm', '#27ae60')]:
                mids = []
                p_logs = []
                for sr in scan_results:
                    key = f"{metric_name}_{pair_suffix}"
                    if key in sr['pairwise']:
                        mid = (sr['band_start'] + sr['band_end']) / 2 + 1
                        mids.append(mid)
                        p_logs.append(-np.log10(max(sr['pairwise'][key]['p'], 1e-50)))

                if mids:
                    ax.plot(mids, p_logs, '-', color=color, linewidth=1.5,
                            alpha=0.8, label=metric_name)

            ax.axhline(y=-np.log10(0.05), color='gray', linestyle='--', alpha=0.5)
            ax.axhline(y=-np.log10(0.001), color='gray', linestyle=':', alpha=0.4)
            ax.set_ylabel('-log₁₀(p)', fontsize=11)
            ax.set_title(pair_label, fontsize=12, fontweight='bold')
            ax.legend(fontsize=9, loc='upper right')
            ax.grid(True, alpha=0.3)

        axes[-1].set_xlabel('Center of PC Window', fontsize=11)
        fig.suptitle(f'Sliding Window Scan (width={CONFIG["scan_width"]}, '
                     f'step={CONFIG["scan_step"]})',
                     fontsize=14, fontweight='bold')
        plt.tight_layout()
        fig.savefig(os.path.join(output_dir, 'fig_spectral_scan.png'),
                    dpi=dpi, bbox_inches='tight')
        plt.close(fig)
        print("  ✓ fig_spectral_scan.png")

    # ── Figure 4 (REMOVED): Internal heatmap superseded by generate_figures.py ──
    # The publication heatmap (fig_spectral_heatmap.png) with prompt-vs-token
    # dual panels is produced by generate_figures.py from summary_spectral.json.

    # ── Figure 5 (REMOVED): T1/T2 effect size figure ──
    # Removed: Type 1 vs Type 2 does not reach significance in any band,
    # so a dedicated figure adds no information.


# ──────────────────────────────────────────────────────────────────────
# REPORT
# ──────────────────────────────────────────────────────────────────────

def write_report(band_results, scan_results, eigenvalues, cumvar, output_dir):
    """Write comprehensive spectral decomposition report."""
    path = os.path.join(output_dir, 'induction_spectral_report.txt')
    lines = []

    lines.append("=" * 90)
    lines.append("SPECTRAL BAND DECOMPOSITION — EIGENSPECTRUM ANALYSIS OF HALLUCINATION SIGNATURES")
    lines.append("=" * 90)
    lines.append(f"\nModel: GPT-2-small (768D hidden states)")
    lines.append(f"PCA components: {len(eigenvalues)}")
    lines.append(f"Bands analyzed: {len(band_results)}")
    lines.append(f"Scan windows: {len(scan_results)}")

    # Eigenspectrum summary
    lines.append("\n" + "─" * 90)
    lines.append("EIGENSPECTRUM")
    lines.append("─" * 90)
    for n in [10, 50, 100, 256, 512]:
        if n <= len(cumvar):
            lines.append(f"  Top {n:>3} PCs: {cumvar[n-1]:.1%} variance")

    # Per-band results
    lines.append("\n" + "─" * 90)
    lines.append("PER-BAND RESULTS")
    lines.append("─" * 90)

    for br in band_results:
        lines.append(f"\n  {br['band_label']} (PCs {br['band_start']+1}–{br['band_end']+1}, "
                     f"{br['n_pcs']} dims, {br['variance_in_band']:.1%} of total variance)")
        lines.append(f"  {'─' * 70}")

        # 3-way tests
        for metric in ['H', 'max_sim', 'norm']:
            if metric in br['tests']:
                t = br['tests'][metric]
                sig = '***' if t['p'] < 0.001 else '**' if t['p'] < 0.01 else '*' if t['p'] < 0.05 else 'ns'
                lines.append(f"    KW {metric:>8}: H={t['H']:>8.2f}, p={t['p']:.2e} {sig}, "
                             f"ε²={t['eps2']:.4f}")

        # Pairwise — focus on Type 1 vs 2
        lines.append(f"    {'─' * 60}")
        for pair_suffix, pair_label in [('type1_vs_type2', 'T1 vs T2'),
                                        ('type1_vs_type3', 'T1 vs T3'),
                                        ('type2_vs_type3', 'T2 vs T3')]:
            for metric in ['H', 'max_sim', 'norm']:
                key = f"{metric}_{pair_suffix}"
                if key in br['pairwise']:
                    pw = br['pairwise'][key]
                    sig = '***' if pw['p'] < 0.001 else '**' if pw['p'] < 0.01 else '*' if pw['p'] < 0.05 else 'ns'
                    lines.append(f"    {pair_label} {metric:>8}: p={pw['p']:.2e} {sig}, "
                                 f"r={pw['r']:+.3f} "
                                 f"({pw['mean_1']:.4f} vs {pw['mean_2']:.4f})")

    # Type 1 vs Type 2: test spectral mixing hypothesis
    lines.append("\n" + "═" * 90)
    lines.append("SPECTRAL MIXING HYPOTHESIS: TYPE 1 vs TYPE 2 BY BAND")
    lines.append("═" * 90)
    lines.append("  (Prompt-level results are the primary inference level)")

    best_t1t2_p = 1.0
    best_t1t2_band = None
    best_t1t2_metric = None

    for br in band_results:
        for metric in ['H', 'max_sim', 'norm']:
            key = f"{metric}_type1_vs_type2"
            if key in br['pairwise']:
                p = br['pairwise'][key]['p']
                r = br['pairwise'][key]['r']
                sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
                label = f"{br['band_label']} / {metric}"
                lines.append(f"  {label:<40} p={p:.2e} {sig:>3}  r={r:+.3f}")
                if p < best_t1t2_p:
                    best_t1t2_p = p
                    best_t1t2_band = br['band_label']
                    best_t1t2_metric = metric

    lines.append(f"\n  Best T1 vs T2 result:")
    lines.append(f"    Band: {best_t1t2_band}")
    lines.append(f"    Metric: {best_t1t2_metric}")
    lines.append(f"    p = {best_t1t2_p:.2e}")
    if best_t1t2_p < 0.05:
        lines.append(f"    Prompt-level significant — spectral mixing hypothesis supported")
    else:
        lines.append(f"    Not significant — spectral mixing hypothesis rejected;")
        lines.append(f"    Type 1/2 non-separation is genuine (capacity hypothesis supported)")

    # Sliding scan summary
    if scan_results:
        lines.append("\n" + "─" * 90)
        lines.append("SLIDING WINDOW SCAN — TYPE 1 vs TYPE 2")
        lines.append("─" * 90)

        scan_best_p = 1.0
        scan_best_window = None
        for sr in scan_results:
            for metric in ['H', 'max_sim', 'norm']:
                key = f"{metric}_type1_vs_type2"
                if key in sr['pairwise']:
                    p = sr['pairwise'][key]['p']
                    if p < scan_best_p:
                        scan_best_p = p
                        scan_best_window = (sr['band_start'], sr['band_end'], metric)

        if scan_best_window:
            lines.append(f"  Best window: PCs {scan_best_window[0]+1}–{scan_best_window[1]+1} "
                         f"({scan_best_window[2]})")
            lines.append(f"  p = {scan_best_p:.2e}")
            if scan_best_p < 0.05:
                lines.append(f"  Significant at token level — verify at prompt level")
            else:
                lines.append(f"  Not significant — no spectral window resolves T1/T2")

            # Bonferroni correction
            n_tests = len(scan_results) * 3  # 3 metrics per window
            bonf_p = min(scan_best_p * n_tests, 1.0)
            lines.append(f"  Bonferroni-corrected (n={n_tests}): p = {bonf_p:.2e}")
            if bonf_p < 0.05:
                lines.append(f"  Survives Bonferroni correction")
            else:
                lines.append(f"  Does not survive Bonferroni correction")

    # Comparison across all four experiments (reference values from prior runs)
    lines.append("\n" + "═" * 90)
    lines.append("FOUR-EXPERIMENT PROGRESSION: TYPE 1 vs TYPE 2")
    lines.append("═" * 90)
    lines.append("  (Reference values from prior experiments; prompt-level p-values)")
    lines.append(f"  Static:             p ≈ 0.47     (Paper 2, Exp 1 — token-level H)")
    lines.append(f"  Raw contextual:     p ≈ 0.59     (Paper 2, Exp 2 — prompt-level H)")
    lines.append(f"  Whitened:           p ≈ 0.65     (Paper 3, Exp 1 — prompt-level H)")
    if best_t1t2_p < 1.0:
        lines.append(f"  Best spectral band: p = {best_t1t2_p:.2e}  (Paper 3, Exp 2 — this run)")
    lines.append(f"  Conclusion: Type 1/2 non-separation is consistent across all four experiments.")

    # Two-level survivor matrix (prompt-level, all bands × metrics × pairs)
    band_labels = [br['band_label'] for br in band_results]
    survivor_lines, survivors = format_survivors_summary(
        band_results, band_labels)
    lines.extend(survivor_lines)

    # Per-band two-level detail for survivors
    lines.append("\n" + "─" * 90)
    lines.append("TWO-LEVEL DETAIL FOR SURVIVING BANDS")
    lines.append("─" * 90)
    for br in band_results:
        band_lines = format_band_report(
            br['band_label'], br, ['H', 'norm', 'max_sim'])
        if len(band_lines) > 1:  # more than just the header
            lines.extend(band_lines)

    lines.append("\n" + "=" * 90)
    lines.append("END OF SPECTRAL DECOMPOSITION REPORT")
    lines.append("=" * 90)

    report = '\n'.join(lines)
    with open(path, 'w') as f:
        f.write(report)

    return report


# ──────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 70)
    print("SPECTRAL BAND DECOMPOSITION — EIGENSPECTRUM ANALYSIS")
    print("=" * 70)
    t_start = time.time()

    os.makedirs(CONFIG['output_dir'], exist_ok=True)

    # Step 1: Load model
    model, tokenizer, static_emb = load_gpt2()

    # Step 2: Build calibration distribution
    calibration_hidden = build_calibration(model, tokenizer)

    # Step 3: Full PCA
    mean, pca, eigenvalues, cumvar = compute_full_pca(calibration_hidden)

    # Step 4: Generate experimental sequences (capture raw hidden states)
    print("\n[Step 4] Generating experimental sequences...")
    all_experimental = []
    for prompts, label in [(TYPE1_PROMPTS, 'type1'),
                           (TYPE2_PROMPTS, 'type2'),
                           (TYPE3_PROMPTS, 'type3')]:
        results = generate_experimental(model, tokenizer, prompts, label)
        all_experimental.extend(results)

    # Free model memory — we only need the hidden states from here
    del model
    gc.collect()

    # Step 5a: Analyze fixed bands
    print("\n[Step 5a] Analyzing spectral bands...")
    t0 = time.time()
    band_results = []
    max_available = len(eigenvalues)
    for start, end, label in CONFIG['bands']:
        if start >= max_available:
            print(f"    Skipping {label} — only {max_available} PCs available")
            continue
        end = min(end, max_available - 1)
        print(f"    Analyzing {label} (PCs {start+1}–{end+1})...")
        r = analyze_band(calibration_hidden, all_experimental, mean, pca,
                         eigenvalues, start, end, label)
        add_legacy_compat(r)
        band_results.append(r)
    print(f"  Band analysis done in {time.time() - t0:.1f}s")

    # Step 5b: Sliding window scan
    scan_results = run_sliding_scan(
        calibration_hidden, all_experimental, mean, pca, eigenvalues,
        CONFIG['scan_width'], CONFIG['scan_step'], CONFIG['scan_max_pc'])
    for sr in scan_results:
        add_legacy_compat(sr)

    # Step 6: Figures (diagnostic — publication figures from generate_figures.py)
    if CONFIG['generate_figures']:
        print("\n[Step 6] Generating diagnostic figures...")
        generate_figures(band_results, scan_results, eigenvalues, cumvar,
                         CONFIG['output_dir'])
    else:
        print("\n[Step 6] Skipping figures (generate_figures=False)")

    # Step 7: Report
    report = write_report(band_results, scan_results, eigenvalues, cumvar,
                          CONFIG['output_dir'])

    # Step 8: Save machine-readable results
    summary = {
        'band_results': [{
            '_meta': br.get('_meta', {}),
            'two_level': results_to_json({k: v for k, v in br.items()
                                          if not k.startswith('_') and k not in
                                          ('band_label', 'band_start', 'band_end',
                                           'n_pcs', 'n_clusters', 'variance_in_band',
                                           'tests', 'pairwise', 'means')}),
            'legacy_pairwise': br.get('pairwise', {}),
        } for br in band_results],
        'scan_summary': [{
            'band_start': sr.get('band_start', sr.get('_meta', {}).get('band_start', 0)),
            'band_end': sr.get('band_end', sr.get('_meta', {}).get('band_end', 0)),
            'tests': sr.get('tests', {}),
            'pairwise': sr.get('pairwise', {}),
        } for sr in scan_results],
        'eigenvalues': eigenvalues[:100].tolist(),
        'cumvar_checkpoints': {
            str(n): float(cumvar[n-1]) for n in [10, 50, 100, 256, 512]
            if n <= len(cumvar)
        },
    }
    with open(os.path.join(CONFIG['output_dir'], 'summary_spectral.json'), 'w') as f:
        json.dump(summary, f, indent=2, default=str)

    print(f"\n{'=' * 70}")
    print(f"COMPLETE — Total runtime: {time.time() - t_start:.1f}s")
    print(f"Results in: {os.path.abspath(CONFIG['output_dir'])}")
    print(f"{'=' * 70}")
    print("\n" + report)


if __name__ == '__main__':
    main()
